type: dev-environment
name: vscode-docker

docker: true
env:
  - MODEL_ID=meta-llama/Llama-3.2-3B-Instruct
  - HF_TOKEN
ide: vscode
files:
  - compose.yaml

# Uncomment to leverage spot instances
#spot_policy: auto

resources:
  gpu: 24GB
