name: Build Hub Docker for STGN

on: [workflow_dispatch]

jobs:
  hub-docker-master:
    defaults:
      run:
        working-directory: docker/hub/stgn
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Build and upload to DockerHub
        run: |
          VERSION=${{ github.run_number }}
          docker buildx build --platform linux/arm64/v8 --push --provenance=false --tag dstackai/dstack-hub-stgn:$VERSION-arm64 -f Dockerfile .
          docker buildx build --platform linux/amd64 --push --provenance=false --tag dstackai/dstack-hub-stgn:$VERSION-amd64 -f Dockerfile .
          docker manifest create dstackai/dstack-hub-stgn:$VERSION --amend dstackai/dstack-hub-stgn:$VERSION-arm64 --amend dstackai/dstack-hub-stgn:$VERSION-amd64
          docker manifest push dstackai/dstack-hub-stgn:$VERSION
          docker manifest create dstackai/dstack-hub-stgn:latest --amend dstackai/dstack-hub-stgn:$VERSION-arm64 --amend dstackai/dstack-hub-stgn:$VERSION-amd64
          docker manifest push dstackai/dstack-hub-stgn:latest
